import Image from "next/image";
import Link from "next/link";
import { CheckCircle2, Clock3 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { buttonClassName } from "@/components/ui/button";
import { SubmitButton } from "@/components/ui/submit-button";
import { acceptQuotationAction } from "@/features/client/commerce-actions";
import type { EngagementRequestRecord } from "@/repositories/engagement-request-repository";
import type { QuotationRecord } from "@/repositories/quotation-repository";

function money(amount: number, currency: string) {
  return `${currency} ${amount.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function QuotationSnapshot({ quotation, accepted }: { quotation: QuotationRecord; accepted?: boolean }) {
  const canAccept = quotation.status === "sent" && new Date(quotation.validUntil) >= new Date();
  return <div className="mx-auto grid w-full max-w-5xl gap-5">
    {accepted ? <p className="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">Quotation accepted. IFTA can now create your engagement.</p> : null}
    <article className="overflow-hidden rounded-md border border-border bg-white text-[#03363D] shadow-lg">
      <header className="flex flex-col justify-between gap-5 bg-[#03363D] px-6 py-6 text-white sm:flex-row sm:items-center"><div className="flex items-center gap-4"><Image alt="IFTA Consulting logo" className="rounded-md bg-white object-contain" height={64} src="/icons/icon-192.png" width={64} /><div><p className="text-xs font-bold uppercase text-[#BDD9D7]">IFTA Consulting (K) Ltd</p><p className="mt-1 text-sm text-white/75">Tax and financial consulting</p></div></div><div className="text-left sm:text-right"><p className="text-xs font-bold uppercase text-[#BDD9D7]">Quotation</p><h1 className="mt-1 text-2xl font-bold">{quotation.number}</h1></div></header>
      <div className="grid gap-8 p-6 md:p-8"><section className="grid gap-5 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-[#557174]">Prepared for</p><p className="mt-2 text-lg font-bold">{quotation.clientName}</p><p className="mt-1 text-sm text-[#557174]">{quotation.clientEmail}</p></div><div className="sm:text-right"><p className="text-sm"><strong>Issued:</strong> {new Intl.DateTimeFormat("en-KE", { dateStyle: "long" }).format(new Date(quotation.issueDate))}</p><p className="mt-2 text-sm"><strong>Valid until:</strong> {new Intl.DateTimeFormat("en-KE", { dateStyle: "long" }).format(new Date(quotation.validUntil))}</p><Badge className="mt-3" tone={quotation.status === "accepted" ? "green" : "gold"}>{quotation.status}</Badge></div></section>
        <div className="overflow-x-auto rounded-md border border-[#cfe0df]"><table className="min-w-[680px] w-full text-left text-sm"><thead className="bg-[#BDD9D7]"><tr><th className="p-3">Service</th><th className="p-3 text-center">Qty</th><th className="p-3 text-right">Unit price</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{quotation.lines.map((line, index) => <tr className="border-t border-[#dce8e7]" key={`${line.description}-${index}`}><td className="p-3 font-semibold">{line.description}</td><td className="p-3 text-center">{line.quantity}</td><td className="p-3 text-right">{money(line.unitPrice, quotation.currency)}</td><td className="p-3 text-right font-bold">{money(line.total, quotation.currency)}</td></tr>)}</tbody></table></div>
        <div className="grid gap-6 md:grid-cols-[minmax(0,1fr)_300px]"><div className="grid content-start gap-4">{quotation.notes ? <div className="border-l-4 border-[#BDD9D7] bg-[#f2f8f7] p-4"><p className="text-xs font-bold uppercase">Notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#38585c]">{quotation.notes}</p></div> : null}<div><p className="text-xs font-bold uppercase text-[#557174]">Terms</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#38585c]">{quotation.terms}</p></div></div><dl className="rounded-md border border-[#cfe0df] p-4"><div className="flex justify-between gap-4 py-2"><dt>Subtotal</dt><dd>{money(quotation.subtotal, quotation.currency)}</dd></div><div className="flex justify-between gap-4 py-2"><dt>Tax ({quotation.taxRate}%)</dt><dd>{money(quotation.taxAmount, quotation.currency)}</dd></div><div className="mt-2 flex justify-between gap-4 border-t-2 border-[#03363D] pt-4 text-lg font-bold"><dt>Total</dt><dd>{money(quotation.total, quotation.currency)}</dd></div></dl></div>
      </div>
      <footer className="flex flex-col justify-between gap-4 border-t border-[#cfe0df] bg-[#BDD9D7] px-6 py-5 sm:flex-row sm:items-center"><div><p className="font-bold">IFTA Consulting (K) Ltd</p><p className="mt-1 text-xs text-[#38585c]">Nairobi, Kenya | Secure client quotation</p></div>{canAccept ? <form action={acceptQuotationAction}><input name="requestId" type="hidden" value={quotation.requestId} /><input name="quotationId" type="hidden" value={quotation.id} /><SubmitButton pendingText="Accepting..."><CheckCircle2 className="h-4 w-4" />Accept quotation</SubmitButton></form> : null}</footer>
    </article>
  </div>;
}

export function QuotationRequestStatus({ request, quotation }: { request: EngagementRequestRecord; quotation: QuotationRecord | null }) {
  if (quotation) return <QuotationSnapshot quotation={quotation} />;
  return <div className="mx-auto grid max-w-4xl gap-5"><section className="rounded-md border border-border bg-card p-5"><Badge tone="teal">{request.reference}</Badge><h1 className="mt-3 text-2xl font-bold text-foreground">Pricing request received</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">The finance team is confirming scope and preparing your formal quotation.</p></section><div className="rounded-md border border-border bg-card"><div className="border-b border-border bg-brand-deep p-5 text-white"><p className="text-xs font-bold uppercase text-brand-mist">Selected services and catalogue pricing</p></div><div className="divide-y divide-border">{request.items.map((item) => <div className="flex flex-col justify-between gap-3 p-5 sm:flex-row sm:items-center" key={item.serviceId}><div><p className="font-semibold text-foreground">{item.serviceTitle}</p><p className="mt-1 text-sm text-muted-foreground">{item.cadence} | Quantity {item.quantity}</p></div><p className="font-bold text-foreground">{item.priceLabel}</p></div>)}</div><div className="flex items-start gap-3 border-t border-border bg-muted/20 p-5"><Clock3 className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-semibold text-foreground">Formal quotation in progress</p><p className="mt-1 text-sm text-muted-foreground">You will receive an in-app alert, device notification and email when it is ready.</p></div></div></div><Link className={buttonClassName({ variant: "secondary", className: "w-fit" })} href="/client/engagements">Back to requests</Link></div>;
}
