export const PERMISSIONS = [
  "clients.read",
  "clients.create",
  "clients.update",
  "clients.archive",
  "staff.read",
  "staff.manage",
  "services.read",
  "services.manage",
  "engagements.read_all",
  "engagements.read_assigned",
  "engagements.create",
  "engagements.accept",
  "engagements.assign",
  "engagements.update_workflow",
  "engagements.complete",
  "engagements.archive",
  "kyc.read",
  "kyc.review",
  "kyc.approve",
  "kyc.assign",
  "kyc.start_review",
  "kyc.approve_requirement",
  "kyc.reject_requirement",
  "kyc.request_replacement",
  "kyc.add_internal_notes",
  "kyc.view_risk",
  "kyc.change_risk",
  "kyc.escalate",
  "kyc.reject",
  "kyc.reopen",
  "kyc.view_audit",
  "kyc.export",
  "kyc.manage_templates",
  "kyc.manage_risk_rules",
  "documents.upload",
  "documents.read_assigned",
  "documents.read_all",
  "documents.review",
  "documents.delete",
  "messages.send",
  "internal_notes.read",
  "internal_notes.create",
  "templates.read",
  "templates.create",
  "templates.edit_draft",
  "templates.submit_review",
  "templates.review",
  "templates.publish",
  "templates.archive",
  "templates.restore",
  "templates.view_usage",
  "templates.manage_ai_prompts",
  "templates.manage_financial",
  "templates.manage_legal",
  "templates.manage",
  "invoices.read",
  "invoices.create",
  "invoices.approve",
  "payments.record",
  "payments.reconcile",
  "reports.read",
  "reports.view_executive",
  "reports.view_clients",
  "reports.view_engagements",
  "reports.view_workflows",
  "reports.view_staff",
  "reports.view_kyc",
  "reports.view_documents",
  "reports.view_finance",
  "reports.view_services",
  "reports.view_communication",
  "reports.view_notifications",
  "reports.view_ai_usage",
  "reports.view_templates",
  "reports.view_archive",
  "reports.view_audit",
  "reports.create_custom",
  "reports.save",
  "reports.share",
  "reports.schedule",
  "reports.export",
  "audit_logs.read",
  "permissions.manage",
  "settings.manage",
  "ai.use",
  "ai.admin",
  "archive.read",
  "archive.view_overview",
  "archive.view_clients",
  "archive.view_engagements",
  "archive.view_documents",
  "archive.view_kyc",
  "archive.view_messages",
  "archive.view_finance",
  "archive.view_templates",
  "archive.view_staff",
  "archive.records",
  "archive.request_restore",
  "archive.approve_restore",
  "archive.restore_records",
  "archive.restore",
  "archive.extend_retention",
  "archive.manage_retention",
  "archive.apply_legal_hold",
  "archive.remove_legal_hold",
  "archive.request_deletion",
  "archive.approve_deletion",
  "archive.permanent_delete",
  "archive.export",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const permissionSet = new Set<string>(PERMISSIONS);

export function isPermission(value: string): value is Permission {
  return permissionSet.has(value);
}

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  "clients.read": "View client profiles and organizations.",
  "clients.create": "Create client organizations and memberships.",
  "clients.update": "Update client profiles and organizations.",
  "clients.archive": "Archive client organizations.",
  "staff.read": "View staff profiles.",
  "staff.manage": "Manage staff profiles and assignments.",
  "services.read": "View service catalogue entries.",
  "services.manage": "Create and update service catalogue entries.",
  "engagements.read_all": "View all engagements.",
  "engagements.read_assigned": "View assigned engagements.",
  "engagements.create": "Create engagement requests.",
  "engagements.accept": "Accept or reject engagement requests.",
  "engagements.assign": "Assign staff to engagements.",
  "engagements.update_workflow": "Update engagement workflow stages and tasks.",
  "engagements.complete": "Complete engagements.",
  "engagements.archive": "Archive engagements.",
  "kyc.read": "View KYC submissions.",
  "kyc.review": "Review KYC documents and questionnaires.",
  "kyc.approve": "Approve KYC submissions.",
  "kyc.assign": "Assign and reassign KYC reviewers.",
  "kyc.start_review": "Start controlled KYC review workflows.",
  "kyc.approve_requirement": "Approve individual KYC requirements.",
  "kyc.reject_requirement": "Reject individual KYC requirements.",
  "kyc.request_replacement": "Request replacement documents for KYC requirements.",
  "kyc.add_internal_notes": "Add staff-only KYC internal notes.",
  "kyc.view_risk": "View internal KYC risk information.",
  "kyc.change_risk": "Change KYC risk classification.",
  "kyc.escalate": "Escalate KYC submissions for senior review.",
  "kyc.reject": "Reject full KYC submissions.",
  "kyc.reopen": "Reopen controlled KYC reviews.",
  "kyc.view_audit": "View KYC audit history.",
  "kyc.export": "Export KYC review data.",
  "kyc.manage_templates": "Manage KYC templates and requirement rules.",
  "kyc.manage_risk_rules": "Manage KYC risk rules and escalation triggers.",
  "documents.upload": "Upload documents.",
  "documents.read_assigned": "View documents for assigned resources.",
  "documents.read_all": "View all permitted documents.",
  "documents.review": "Review documents.",
  "documents.delete": "Soft-delete documents.",
  "messages.send": "Send engagement-linked messages.",
  "internal_notes.read": "View staff-only internal notes.",
  "internal_notes.create": "Create staff-only internal notes.",
  "templates.read": "View template categories, versions and metadata.",
  "templates.create": "Create new template drafts.",
  "templates.edit_draft": "Edit draft template versions.",
  "templates.submit_review": "Submit draft templates for review.",
  "templates.review": "Review templates awaiting approval.",
  "templates.publish": "Publish approved template versions.",
  "templates.archive": "Archive templates and template versions.",
  "templates.restore": "Restore archived templates.",
  "templates.view_usage": "View where templates and versions have been used.",
  "templates.manage_ai_prompts": "Manage AI prompt templates and review rules.",
  "templates.manage_financial": "Manage invoice and financial templates.",
  "templates.manage_legal": "Manage legal and engagement letter templates.",
  "templates.manage": "Manage templates.",
  "invoices.read": "View invoices.",
  "invoices.create": "Create invoices.",
  "invoices.approve": "Approve invoices.",
  "payments.record": "Record payments.",
  "payments.reconcile": "Reconcile payments.",
  "reports.read": "View reports and analytics.",
  "reports.view_executive": "View executive overview reports.",
  "reports.view_clients": "View client reports.",
  "reports.view_engagements": "View engagement reports.",
  "reports.view_workflows": "View workflow and task reports.",
  "reports.view_staff": "View staff performance and capacity reports.",
  "reports.view_kyc": "View KYC and compliance reports.",
  "reports.view_documents": "View document activity reports.",
  "reports.view_finance": "View finance, invoice and payment reports.",
  "reports.view_services": "View service performance reports.",
  "reports.view_communication": "View communication reports.",
  "reports.view_notifications": "View notification reports.",
  "reports.view_ai_usage": "View AI usage reports.",
  "reports.view_templates": "View template usage reports.",
  "reports.view_archive": "View archive and retention reports.",
  "reports.view_audit": "View audit and security reports.",
  "reports.create_custom": "Create custom reports.",
  "reports.save": "Save report configurations.",
  "reports.share": "Share reports internally.",
  "reports.schedule": "Schedule report delivery.",
  "reports.export": "Export reports.",
  "audit_logs.read": "View audit logs.",
  "permissions.manage": "Manage roles and permissions.",
  "settings.manage": "Manage system settings.",
  "ai.use": "Use AI workspaces.",
  "ai.admin": "Administer AI usage and prompts.",
  "archive.read": "View archived workspaces.",
  "archive.view_overview": "View archive overview and records-management dashboard.",
  "archive.view_clients": "View archived client records.",
  "archive.view_engagements": "View archived engagement records.",
  "archive.view_documents": "View archived documents.",
  "archive.view_kyc": "View archived KYC records.",
  "archive.view_messages": "View archived messages and conversations.",
  "archive.view_finance": "View archived finance records.",
  "archive.view_templates": "View archived templates.",
  "archive.view_staff": "View archived staff records.",
  "archive.records": "Archive eligible records.",
  "archive.request_restore": "Request restoration of archived records.",
  "archive.approve_restore": "Approve archive restore requests.",
  "archive.restore_records": "Restore archived records after approval.",
  "archive.restore": "Restore archived resources.",
  "archive.extend_retention": "Extend retention periods for archived records.",
  "archive.manage_retention": "Manage archive retention policies.",
  "archive.apply_legal_hold": "Apply legal holds to archived records.",
  "archive.remove_legal_hold": "Remove legal holds from archived records.",
  "archive.request_deletion": "Request deletion of retention-expired records.",
  "archive.approve_deletion": "Approve deletion requests.",
  "archive.permanent_delete": "Permanently delete or anonymize eligible records.",
  "archive.export": "Export archive summaries and records.",
};
